
export const SYLLABUS_CONTENT = `
CMS Certified Consultant 13 LTS (Syllabus Status: 2026) - DEEP DIVE KNOWLEDGE

--- DOMAIN: TYPO3 Basics & Architecture (Linked Docs Content) ---
* **Directory Structure (v13 Composer):**
  * \`public/index.php\`: Entry point.
  * \`config/system/settings.php\`: Local system configuration (DB credentials).
  * \`config/system/additional.php\`: Manual overrides.
  * \`var/\`: Temporary data (cache, logs, locks) - must be writable, should NOT be in Git.
  * \`vendor/\`: Composer packages.
* **Application Context:**
  * Define via env variable \`TYPO3_CONTEXT\` (Production, Development, Testing).
  * Influences caching behavior, error display, and logging.
  * Presets in \`system.yaml\` can react to context.

--- DOMAIN: TYPO3 Administration & Site Handling (Linked Docs Content) ---
* **Site Configuration (YAML):**
  * Stored in \`config/sites/<identifier>/config.yaml\`.
  * **Entry Point:** Defined by \`rootPageId\` and \`base\`.
  * **Site Sets (New in v13):**
    * Replaces legacy TypoScript inclusion in sys_template.
    * Defined in extensions via \`Configuration/Sets/\`.
    * Included in \`config.yaml\` via \`dependencies: - my-site-package\`.
    * Allows encapuslating TypoScript, TSConfig, and Site Settings.
  * **Error Handling:** Configured in YAML (HTTP 404, 403, 500 handling -> redirect to page or show content).
  * **Languages:** Defined in \`config.yaml\`. Strict distinction between "Site Language" (Config) and "Sys Language" (DB Record).
  * **Routing:** Slugs are generated from page titles. Conflicts must be handled (unique in site).

--- DOMAIN: Security & Hardening (Linked Docs Content) ---
* **Guidelines:**
  * **trustedHostsPattern:** Protects against Host Header Injection. Must match the domain.
  * **lockSSL:** Force HTTPS backend usage.
  * **fileDenyPattern:** Prevent execution of .php files in /public/fileadmin.
  * **Directory Listing:** Must be disabled in Webserver (Apache Options -Indexes).
* **Cookies & Sessions:**
  * \`SameSite\` cookie strategy (Lax/Strict) to prevent CSRF.
  * \`cookies_secure\`: Only send cookies over HTTPS.
* **Incident Response:**
  * 1. **Prevent:** Hardening, Updates.
  * 2. **Detect:** Monitoring, IDS, Log analysis.
  * 3. **Respond:** Take offline, Analyze (Forensics), Clean.
  * 4. **Recover:** Restore safe backup, Reset credentials, Patch entry point.

--- DOMAIN: Extensions & Composer (Linked Docs Content) ---
* **Composer Basics:**
  * \`composer.json\`: Main definition. \`require\` (prod dependencies), \`require-dev\` (testing tools).
  * \`composer.lock\`: Locks exact versions. MUST be committed to Git.
  * Commands: \`composer install\` (deploy), \`composer update\` (upgrade versions).
* **Semantic Versioning:** MAJOR.MINOR.PATCH (e.g., 13.4.1).
  * Tilde (~13.4): Allows 13.4.x, but not 13.5.
  * Caret (^13.4): Allows 13.x.x, but not 14.0.
* **Extension Architecture:**
  * \`ext_emconf.php\`: Legacy metadata (still needed for TER).
  * \`ext_localconf.php\`: Global configuration (Hooks, Scheduler tasks).
  * \`ext_tables.php\`: Backend module registration (Legacy).
  * \`Configuration/TCA\`: Database definition (Table Configuration Array).

--- DOMAIN: SEO & Performance (Linked Docs Content) ---
* **Technical SEO:**
  * **Canonical Tags:** Prevent Duplicate Content issues. Auto-generated by TYPO3, can be overridden.
  * **Hreflang:** Automagically generated by Site Handling for multi-language sites.
  * **Robots.txt:** Virtual in v13 (Site Settings) or physical file.
  * **XML Sitemap:** Scheduler task or on-the-fly generation via SEO extension.
* **Caching Framework:**
  * **Pages Cache:** Stores full HTML output.
  * **Internal Caches:** PHP code cache, Rootline cache.
  * **Clear Cache cmds:** "Flush Frontend" (clears page output), "Flush All" (clears system caches).
  * **Varnish:** Reverse Proxy. Needs "Proxy Header" configuration in TYPO3 to handle IP detection correctly.

--- DOMAIN: TypoScript (Linked Docs Content) ---
* **Purpose:**
  * **Configuration:** It configures the rendering (Frontend TypoScript) and the Backend interface (TSConfig).
  * **NOT Programming:** It is a declarative configuration array, converted to a PHP array. No loops/logic in the traditional sense (use DataProcessors for that).
* **Syntax:**
  * Dot notation (page.10 = TEXT).
  * Copy (<) vs Reference (=<).
  * Conditions: \`[frontend.user.isLoggedIn]\`.
* **DataProcessors:** The modern way to get data into Fluid (replacing old cObject logic).

--- DOMAIN: Accessibility (Linked Docs Content) ---
* **WCAG 2.1 Levels:** A (Minimum), AA (Standard/Legal requirement in EU/BITV), AAA (Highest).
* **Images:** Alt-text is mandatory for informative images, empty (alt="") for decorative.
* **Structure:** Correct heading hierarchy (H1 -> H2 -> H3), Landmarks (nav, main, footer).
* **Keyboard:** Focus states must be visible. Skip-links for navigation.
`;